app/energymeter/models.py
# Import the database object (db) from the main application module
# We will define this inside /app/__init__.py in the next sections.
from app import db

# Import datetime for time functions
from datetime import datetime

# Import pandas
import pandas as pd

import pickle

# Import costs from config file
from config import KWH_COST, STANDING_CHARGE



class Reading(db.Model):

	__tablename__  	=	'reading'
	
	id            	= 	db.Column(db.Integer, primary_key=True)
	timestamp		=	db.Column(db.DateTime)
	watt			=	db.Column(db.Integer)
	temperature		=	db.Column(db.Float)
	
	def __init__(self, watt, temp):
		self.timestamp		=	datetime.now()
		self.watt			=	watt
		self.temperature	=	temp

# You should be able to use an abstract class for some of the attributes and methods of the classes below

class Day(db.Model):

	__tablename__  	=	'day'
	
	id            	= 	db.Column(db.Integer, primary_key=True)
	# Number of day in year - e.g. 1 to 365 / 366
	number			=	db.Column(db.Integer)
	date			=	db.Column(db.Date)
	year			=	db.Column(db.Integer)
	dataframe		=	db.Column(db.PickleType)
	# Number of kwhs used in the day
	units_used		=	db.Column(db.Numeric)
	# Cost of units used
	cost_units		=	db.Column(db.Numeric)
	# Total cost including standing charge
	cost_total		=	db.Column(db.Numeric)
	
	def __init__(self, date):
		self.date 	= 	date
		self.number	=	date.timetuple().tm_yday
		self.year	=	date.timetuple().tm_year
	
	@classmethod
	def get(cls, date, create=False):
		# Method to get a day record for a supplied date - if create=true the method will create and return a new day object if no pre-existing object exists
		existing_day	=	cls.query.filter(cls.date == date.date()).first()
		if not existing_day and create:
			existing_day 	=	cls(date)
			db.session.add(existing_day)
			db.session.commit()
		if existing_day:
			return existing_day
		else:
			return None
			
	@classmethod
	def generate_all(cls, overwrite=False):
		# Generate day records for all days where we have recorded timestamps
		# Get list of distinct dates in Reading
		distinct_dates = db.session.query(db.func.DATE(Reading.timestamp)).distinct().all()
		# Convert to datetime objectd
		distinct_dates = [datetime.strptime(date[0], '%Y-%m-%d') for date in distinct_dates]
		for date in distinct_dates:
			if not cls.get(date) or overwrite:
				new_day = cls.get(date, create=True)
				new_day.get_cost(overwrite=True)
	
	def get_dataframe(self, overwrite=False):
		# Method to generate and store dataframe
		#if overwrite=True a new dataframe will be generated and the old frame will be overwritten
		#if overwrite=False no new dataframe will be generated if one already exists
		if self.dataframe and not overwrite:
			return pickle.loads(self.dataframe)
		else:
			columns 		= 	[c.name for c in Reading.__table__.columns]
			columns.remove("id")
			def make_row(x):
				return dict([(c, getattr(x, c)) for c in columns])
			query 			= 	Reading.query.filter(db.func.date(Reading.timestamp) == self.date)
			dataframe	=	pd.DataFrame([make_row(x) for x in query])
			
			dataframe.index = pd.to_datetime(dataframe.pop("timestamp"))
			#Resample to standard 2minute intervals
			dataframe = dataframe.resample("2T", how="mean")
			# Resample here to common timebase? e.g. every 2mins + fill missmg data
			start = datetime(self.date.year, self.date.month, self.date.day, 0, 0)
			end = datetime(self.date.year, self.date.month, self.date.day, 23, 59)
			dayrange = pd.date_range(start, end, freq="2min")
			dataframe = dataframe.reindex(dayrange)
			dataframe.sort_index
			self.dataframe = pickle.dumps(dataframe)
			db.session.add(self)
			db.session.commit()
			return dataframe
	
	def get_cost(self, overwrite=False):
		if not (self.units_used and self.cost_units and self.cost_total) or overwrite:
			df = self.get_dataframe(overwrite=True)
			df_hour = df["watt"].resample("1H", how="sum")
			df_kwh = df_hour/(30*1000)
			self.units_used = df_kwh.sum()
			self.cost_units = (KWH_COST*self.units_used)/100
			self.cost_total = self.cost_units + STANDING_CHARGE/100
			db.session.add(self)
			db.session.commit()
		return {
					'units_used'	:	format(self.units_used, ',.2F'), 
					'cost_units'	:	format(self.cost_units, ',.2F'),
					'cost_total'	:	format(self.cost_total, ',.2F')
					}
	
	def get_plot(self, yaxis="W"):
		# Returns a plot of hourly energy usage for "W" or temperature for "T"
		pass
		



class Week(db.Model):

	__tablename__  	=	'week'
	
	id            	= 	db.Column(db.Integer, primary_key=True)
	# Number of week in year - from 1 to 52
	number			=	db.Column(db.Integer)
	year			=	db.Column(db.Integer)
	dataframe		=	db.Column(db.PickleType)
	# Number of kwhs used in the week
	units_used		=	db.Column(db.Numeric)
	# Cost of units used in the week
	cost_units		=	db.Column(db.Numeric)
	# Total cost including standing charge for the week
	cost_total		=	db.Column(db.Numeric)
	# Average daily usage for the week
	av_day_units	=	db.Column(db.Numeric)
	# Average daily cost for the week
	av_day_tcost	=	db.Column(db.Numeric)
	
	# Use function to return start date / end date
	
	def get_plot(self, yaxis="W"):
		# Returns a plot of daily energy usage for the week "W" or average hourly temperature over the week for "T"
		pass

class Month(db.Model):

	__tablename__  	=	'month'

	id            	= 	db.Column(db.Integer, primary_key=True)
	# Number of month in year - from 1 to 12
	number			=	db.Column(db.Integer)
	year			=	db.Column(db.Integer)
	dataframe		=	db.Column(db.PickleType)

class Year(db.Model):

	__tablename__  	=	'year'
	
	id            	= 	db.Column(db.Integer, primary_key=True)
	year			=	db.Column(db.Integer)
	
	# Use function to return the 12 month dataframes

app/__init__.py
# Import flask and template operators
from flask import Flask, render_template

# Import SQLAlchemy
from flask.ext.sqlalchemy import SQLAlchemy

# Define the WSGI application object
app = Flask(__name__)

# Configurations
app.config.from_object('config')

# Define the database object which is imported
# by modules and controllers
db = SQLAlchemy(app)

# Sample HTTP error handling
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

# Import a module / component using its blueprint handler variable
from app.energymeter.controllers import energymeter as em

# Import jinja2 filters
#from app.template_filters.filters import filters

app.jinja_env.lstrip_blocks = True
app.jinja_env.trim_blocks = True

# Register blueprint(s)
app.register_blueprint(em)

#app.register_blueprint(filters)
# ..

# Build the database:
# This will create the database file using SQLAlchemy
db.create_all()

app/energymeter/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for

# Import the database object from the main app module
from app import db

# Import login manager login_required decorator - is there a way to avoid having to add this to all functions in a separate blueprint?
#from flask.ext.login import login_required

# Import module forms
#from app.energymeter.forms import 

# Import module models
from app.energymeter.models import Reading, Day

# Define the blueprint: 'energymeter'
energymeter = Blueprint('energymeter', __name__)

# Import configuration settings
from config import RECORDS_PER_PAGE

@energymeter.route('/', methods=['GET', 'POST'])
@energymeter.route('/index', methods=['GET', 'POST'])
@energymeter.route('/index/<int:page>', methods=['GET', 'POST'])
def index(page=1):
	readings = Reading.query.order_by(Reading.timestamp.desc()).paginate(page, RECORDS_PER_PAGE, False)
	return render_template('dataview.html', readings=readings)
	
@energymeter.route('/day', methods=['GET'])
def showdaydata():
	Day.generate_all()
	days = Day.query.order_by(Day.date.desc())
	
	return render_template('dayview.html', days=days)

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		{% block head %}
		<meta name="description" content="energy monitor dashboard">
		<meta name="author" content="Ben Hoyle">
		<meta name="format-detection" content="telephone=no" />
		<!--<link rel="icon" href="../../favicon.ico">-->
		<title>{% block title %}{% endblock %}</title>
		<!-- Bootstrap core CSS -->
		<link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">
		<!-- Bootstrap dashboard CSS -->
		<link href="{{ url_for('static', filename='dashboard.css') }}" rel="stylesheet">
		{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Energy Monitor</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#">Dashboard</a></li>
						<li><a href="#">Settings</a></li>
						<li><a href="#">Profile</a></li>
						<li><a href="#">Help</a></li>
					</ul>
					<!-- Optional search bar
					<form class="navbar-form navbar-right">
						<input type="text" class="form-control" placeholder="Search...">
					</form>-->
				</div>
			</div>
		</nav>
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3 col-md-2 sidebar">
					<ul class="nav nav-sidebar">
						<li class="active"><a href="{{ url_for('energymeter.index') }}">Readings <span class="sr-only">(current)</span></a></li>
						<li><a href="{{ url_for('energymeter.showdaydata') }}">Days</a></li>
						<li><a href="#">Weeks</a></li>
						<li><a href="#">Months</a></li>
						<li><a href="#">Years</a></li>
					</ul>
					{#<ul class="nav nav-sidebar">
						<li><a href="">Nav item</a></li>
						<li><a href="">Nav item again</a></li>
						<li><a href="">One more nav</a></li>
						<li><a href="">Another nav item</a></li>
						<li><a href="">More navigation</a></li>
					</ul>
					<ul class="nav nav-sidebar">
						<li><a href="">Nav item again</a></li>
						<li><a href="">One more nav</a></li>
						<li><a href="">Another nav item</a></li>
					</ul>#}
				</div>
				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>
		{% block javascript %}
		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
		<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
		{% endblock %}
	</body>
</html>

app/templates/dataview.html
{% extends "dashboard.html" %}

{% block title %}Energy Meter Readings{% endblock %}

{% block content %}

<h1 class="page-header">Dashboard</h1>
{#
<div class="row placeholders">
	<div class="col-xs-6 col-sm-3 placeholder">
		<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
		<h4>Label</h4>
		<span class="text-muted">Something else</span>
	</div>
	<div class="col-xs-6 col-sm-3 placeholder">
		<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
		<h4>Label</h4>
		<span class="text-muted">Something else</span>
	</div>
	<div class="col-xs-6 col-sm-3 placeholder">
		<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
		<h4>Label</h4>
		<span class="text-muted">Something else</span>
	</div>
	<div class="col-xs-6 col-sm-3 placeholder">
		<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
		<h4>Label</h4>
		<span class="text-muted">Something else</span>
	</div>
</div>
#}
<h2 class="sub-header">Meter Readings</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Timestamp</th>
				<th>Watts</th>
				<th>Temp</th>
		</thead>
		<tbody>
			{% for reading in readings.items %}
			<tr>
				<td>{{ reading.timestamp }}</td>
				<td>{{ reading.watt }}</td>
				<td>{{ reading.temperature }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
<ul class = "pager">
	{% if readings.has_prev %}<li class = "previous"><a href="{{ url_for('energymeter.index', page=readings.prev_num) }}">&lt;&lt; Newer readings</a>{% else %}<li class = "previous disabled"><a href="">&lt;&lt; Newer readings</a>{% endif %} | 
	{% if readings.has_next %}<li class = "next"><a href="{{ url_for('energymeter.index', page=readings.next_num) }}">Older readings &gt;&gt;</a>{% else %}<li class = "next disabled"><a href="">Older readings &gt;&gt;</a>{% endif %}
</ul>
{% endblock %}

app/templates/dayview.html
{% extends "dashboard.html" %}

{% block title %}Energy Meter - Daily Electricity Usage{% endblock %}

{% block content %}

<h1 class="page-header">Days</h1>
{% for day in days %}
{# Start a new row every xth day #}
{% set cols_per_row = 3 %}
{% set col_width = (12//cols_per_row) %}
{% if (loop.index is divisibleby (cols_per_row+1)) or (loop.first) %}
<div class="row">
{% endif %}

<div class="col-sm-{{col_width}}">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="text-center">{{ day.date }}</h4>
		</div>
		<table class="table">
			<tr>
				<td>Units Used:</td>
				<td><h5 class="text-center">{{ day.units_used|round(2, 'ceil') }} kwh</h5></td>
			</tr>
			<tr>
				<td>Cost of Units:</td>
				<td><h5 class="text-center">£{{ day.cost_units|round(2, 'ceil') }}</h5></td>
			</tr>
			<tr>
				<td>Cost (inc. standing):</td>
				<td><h5 class="text-center">£{{ day.cost_total|round(2, 'ceil') }}</h5></p></td>
			</tr>
		</table>
	</div>
</div>

{% if ((loop.index+1) is divisibleby (cols_per_row+1)) or (loop.last) %}
</div>
{% endif %}

{% endfor %}

{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Graph Energy Monitor Data</title>
        <link type="text/css" rel="stylesheet" href="/static/main.css" />
    </head>
    <body>
    	<h1>Energy Monitor Graphing</h1>
		<form method="POST">
		<div class="input">
		<table>
			<tr>
				<td>
					<label>
						Select Variable
					</label>
				</td>
				<td>
					<select name="variable">
						<option>Watts</option>
						<option>Temperature</option>
			        </select>
				</td>
			</tr>
			<tr>
				<td>
					<label>
						Select Units
					</label>
				</td>
				<td>
					 <select name="units">
						<option>Minutes</option>
						<option>Hours</option>
						<option>Days</option>
						<option>Weeks</option>
						<option>Months</option>
						<option>Years</option>
			        </select>
				</td>
			</tr>
			<tr>
				<td><label>Enter Start Date/Time for Range:</label></td>
				<td><input type="datetime-local" name="startdatetime"></td>
			</tr>
			<tr>
				<td><label>Enter End Date/Time for Range:</label></td>
				<td><input type="datetime-local" name="enddatetime"></td>
			</tr>
        </table>
        <div class="submit">
			<input type="submit" value="Plot Graph">
        </div>
        </form>
        </div>
<!--
        <div class="output">
        <figure>
			<embed type="image/svg+xml" src="energy.svg" />
		</figure>
        </div>
-->
    </body>
</html>

app/templates/readings.html
<!DOCTYPE html>
<html>
    <head>
        <title>Graph Energy Monitor Data</title>
    </head>
    <body>
    {%for row in rows %}
		{{ row }}
		<br><br>
	{% endfor %}
	</body>
</html>
    